default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: poetry run ruff check --force-exclude --show-source
        'types_or':
          - python
          - pyi
        require_serial: true
        language: system
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: ".ambr"
      - id: check-ast
        name: Check python abstract syntax trees
      - id: check-case-conflict
        name: Check for case conflicts
      - id: check-json
      - id: check-yaml
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: end-of-file-fixer
        name: Files should end with empty line
        exclude: ".json"
      - id: name-tests-test
        name: Tests should begin with test_
        args: ["--django"]
        exclude: "^(?!helpers/)"
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.3.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-export
        args: [ "--without-hashes", "--format", "requirements.txt", "--output", "requirements.txt" ]
