name: Build & Test Main 🧪
on:
  push:
    branches: [main]
concurrency: ci-${{ github.ref}}-${{ github.event_name }}
permissions:
  id-token: write
  contents: read
jobs:
  build-and-test:

    if: ${{ !contains( github.event.head_commit.message, 'skip-ci' ) }}
    uses: ./.github/workflows/build-test-common.yml
    with:
      ref: ${{ github.ref }}
      e2e_stack_env: ci
    secrets:
      GHA_TOKEN: ${{ secrets.GHA_TOKEN }}
      GHA_OIDC_ROLE: ${{ secrets.GHA_OIDC_ROLE }}
